-- User settings
require("user")
-- Plugin management via Packer
require("plugins")
-- Global keyboard and which-key mappings
require("mappings")
-- Vim options
require("options")
-- Vim autocommands/autogroups
require("autocmd")
-- Plugin configurations
require("plugins/autopairs")
require("plugins/comment")
require("plugins/bufferline")
require("plugins/colorizer")
require("plugins/cmp")
require("plugins/diffview")
require("plugins/formatter")
require("plugins/lf")
require("plugins/lsp")
require("plugins/lualine")
require("plugins/neogit")
require("plugins/git-blame")
require("plugins/gitsigns")
require("plugins/navigator")
require("plugins/nvim-tree")
require("plugins/project")
require("plugins/symbols")
require("plugins/telescope")
require("plugins/todo")
require("plugins/toggleterm")
require("plugins/treesitter")
require("plugins/trouble")
require("plugins/vsnip")
require("plugins/which")
